version: '3.8'

services:
  front-end:
    build:
      context: ./front-end
    ports:
      - "80:80"
    depends_on:
      - proxy

  proxy:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - back-end

  back-end:
    build:
      context: ./back-end
    deploy:
      replicas: 2
    ports:
      - "5252"
    expose:
      - "5252"
